정원혁 William, 2020, D+
# Overall Outline

1. Read Data

2. Independent variable / Dependent variable: Ranking / ......
    - Remove unnecessary columns
    - (Create additional necessary columns)
3. Handle NA values
4. Handle outliers
5. Dummy encoding
    - Convert categorical / numerical variables using astype()
    - For numerical variables: scale transformation
        min / max scale
        mean / std scale
6. Split into train / test sets
7. Declare model
8. Train model
9. Predict
10. Performance
    - MSE, R-square
    - Accuracy



# 1. Read Data

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Read Data
data = pd.read_csv('https://raw.githubusercontent.com/Peter-Mfitumukiza/ai-class/main/Iris%20classification/iris.csv')

data

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# 2. Independent variable / Dependent variable: Ranking / ......
    - Remove unnecessary columns
    - (Create additional necessary columns)

In [2]:
X = data.drop('class', axis=1)
y = data['class']

# 3. Handle NA values

# 5. Split into train / test sets

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 6. Dummay enconding / Scaling

> Add blockquote




In [4]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 7. Declare model


In [5]:
model = LogisticRegression(random_state=42, multi_class='ovr')

# 8. Train model

In [6]:
model.fit(X_train_scaled, y_train)

LogisticRegression(multi_class='ovr', random_state=42)

# 9. Predict


In [7]:
y_pred = model.predict(X_test_scaled)

# Create a table with actual and predicted values
results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})

results

Actual        Predicted
73   Iris-versicolor  Iris-versicolor
18       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
78   Iris-versicolor  Iris-versicolor
76   Iris-versicolor  Iris-versicolor
31       Iris-setosa      Iris-setosa
64   Iris-versicolor  Iris-versicolor
141   Iris-virginica   Iris-virginica
68   Iris-versicolor  Iris-versicolor
82   Iris-versicolor  Iris-versicolor
110   Iris-virginica   Iris-virginica
12       Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
9        Iris-setosa      Iris-setosa
19       Iris-setosa      Iris-setosa
56   Iris-versicolor   Iris-virginica
104   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
55   Iris-versicolor  Iris-versicolor
132   Iris-virginica   Iris-virginica
29       Iris-setosa      Iris-setosa
127   Iris-virginica   Iris-virginica
26       Iris-setosa      Iris-setosa
128   Iris-virginica   Iris-virginica
131   Iris-virginica   Iris-virginica
145   Iris-virginica   Iris-virginica
108   Iris-virginica   Iris-virginica
143   Iris-virginica   Iris-virginica
45       Iris-setosa      Iris-setosa
30       Iris-setosa      Iris-setosa

# 10. Performance
    - confusion matrix
    - classification report


In [8]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.89      0.94         9
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.97        30
   weighted avg       0.97      0.97      0.97        30

